export const LOCALIZATION_SERVICE = Symbol('LOCALIZATION_SERVICE');
export const PAGINATION_SERVICE = Symbol('PAGINATION_SERVICE');
export const TRANSACTION_MANAGER_SERVICE = Symbol(
  'TRANSACTION_MANAGER_SERVICE',
);
export const TRANSFORM_RESULT_SERVICE = Symbol('TRANSFORM_RESULT_SERVICE');

export const IMAGE_FOLDER = process.env.IMAGE_FOLDER || 'uploads';
export const MAX_IMAGE_SIZE = 10 * 1024 * 1024;
export const IMAGE_ALLOW_MIME_TYPE = [
  'image/png',
  'image/jpg',
  'image/jpeg',
  'image/gif',
  'image/webp',
];

export const OTP_LENGTH = 6;
export const E_COMMERCE = 'E';
export const MIN_GENERATE_CODE_LENGTH = 1;
export const MAX_GENERATE_CODE_LENGTH = 6;

export const QUEUE_SERVICE = Symbol('QUEUE_SERVICE');

export const USER_PROFILE_IMAGE_FILE_OPTIMIZE_SERVICE_KEY = Symbol(
  'USER_PROFILE_IMAGE_FILE_OPTIMIZE_SERVICE_KEY',
);

export const JWT_SERVICE = Symbol('JWT_SERVICE');

export const AUTH_SERVICE = Symbol('AUTH_SERVICE');
export const WRITE_AUTH_REPOSITORY = Symbol('WRITE_AUTH_REPOSITORY');
export const READ_AUTH_REPOSITORY = Symbol('READ_AUTH_REPOSITORY');

export const USER_SERVICE = Symbol('USER_SERVICE');
export const WRITE_USER_REPOSITORY = Symbol('WRITE_USER_REPOSITORY');
export const READ_USER_REPOSITORY = Symbol('READ_USER_REPOSITORY');

export const ROLE_SERVICE = Symbol('ROLE_SERVICE');
export const WRITE_ROLE_REPOSITORY = Symbol('WRITE_ROLE_REPOSITORY');
export const READ_ROLE_REPOSITORY = Symbol('READ_ROLE_REPOSITORY');

export const PERMISSION_SERVICE = Symbol('PERMISSION_SERVICE');
export const READ_PERMISSION_REPOSITORY = Symbol('READ_PERMISSION_REPOSITORY');

export const USER_PROFILE_SERVICE = Symbol('USER_PROFILE_SERVICE');
export const WRITE_USER_PROFILE_REPOSITORY = Symbol(
  'WRITE_USER_PROFILE_REPOSITORY',
);
export const READ_USER_PROFILE_REPOSITORY = Symbol(
  'READ_USER_PROFILE_REPOSITORY',
);

export const BANNER_SERVICE = Symbol('BANNER_SERVICE');
export const WRITE_BANNER_REPOSITORY = Symbol('WRITE_BANNER_REPOSITORY');
export const READ_BANNER_REPOSITORY = Symbol('READ_BANNER_REPOSITORY');

export const BRAND_SERVICE = Symbol('BRAND_SERVICE');
export const WRITE_BRAND_REPOSITORY = Symbol('WRITE_BRAND_REPOSITORY');
export const READ_BRAND_REPOSITORY = Symbol('READ_BRAND_REPOSITORY');

export const SUPPLIER_SERVICE = Symbol('SUPPLIER_SERVICE');
export const WRITE_SUPPLIER_REPOSITORY = Symbol('WRITE_SUPPLIER_REPOSITORY');
export const READ_SUPPLIER_REPOSITORY = Symbol('READ_SUPPLIER_REPOSITORY');

export const TAG_SERVICE = Symbol('TAG_SERVICE');
export const WRITE_TAG_REPOSITORY = Symbol('WRITE_TAG_REPOSITORY');
export const READ_TAG_REPOSITORY = Symbol('READ_TAG_REPOSITORY');

export const CATEGORY_SERVICE = Symbol('CATEGORY_SERVICE');
export const WRITE_CATEGORY_REPOSITORY = Symbol('WRITE_CATEGORY_REPOSITORY');
export const READ_CATEGORY_REPOSITORY = Symbol('READ_CATEGORY_REPOSITORY');

export const CATEGORY_DETAIL_SERVICE = Symbol('CATEGORY_DETAIL_SERVICE');
export const WRITE_CATEGORY_DETAIL_REPOSITORY = Symbol(
  'WRITE_CATEGORY_DETAIL_REPOSITORY',
);
export const READ_CATEGORY_DETAIL_REPOSITORY = Symbol(
  'READ_CATEGORY_DETAIL_REPOSITORY',
);

export const TAX_SERVICE = Symbol('TAX_SERVICE');
export const WRITE_TAX_REPOSITORY = Symbol('WRITE_TAX_REPOSITORY');
export const READ_TAX_REPOSITORY = Symbol('READ_TAX_REPOSITORY');

export const WRITE_ROLE_PERMISSION_REPOSITORY = Symbol(
  'WRITE_ROLE_PERMISSION_REPOSITORY',
);

export const STORE_SERVICE = Symbol('STORE_SERVICE');
export const WRITE_STORE_REPOSITORY = Symbol('WRITE_STORE_REPOSITORY');
export const READ_STORE_REPOSITORY = Symbol('READ_STORE_REPOSITORY');

export const STORE_USER_SERVICE = Symbol('STORE_USER_SERVICE');
export const WRITE_STORE_USER_REPOSITORY = Symbol(
  'WRITE_STORE_USER_REPOSITORY',
);
export const READ_STORE_USER_REPOSITORY = Symbol('READ_STORE_USER_REPOSITORY');

export const WRITE_OPEN_CLOSE_STORE_REPOSITORY = Symbol(
  'WRITE_OPEN_CLOSE_STORE_REPOSITORY',
);
export const READ_OPEN_CLOSE_STORE_REPOSITORY = Symbol(
  'READ_OPEN_CLOSE_STORE_REPOSITORY',
);

export const WRITE_USER_PERMISSION_REPOSITORY = Symbol(
  'WRITE_USER_PERMISSION_REPOSITORY',
);

export const PROVINCE_SERVICE = Symbol('PROVINCE_SERVICE');
export const READ_PROVINCE_REPOSITORY = Symbol('READ_PROVINCE_REPOSITORY');

export const DISTRICT_SERVICE = Symbol('DISTRICT_SERVICE');
export const READ_DISTRICT_REPOSITORY = Symbol('READ_DISTRICT_REPOSITORY');

export const VILLAGE_SERVICE = Symbol('VILLAGE_SERVICE');
export const READ_VILLAGE_REPOSITORY = Symbol('READ_VILLAGE_REPOSITORY');

export const PRODUCT_ATTRIBUTE_SERVICE = Symbol('PRODUCT_ATTRIBUTE_SERVICE');
export const WRITE_PRODUCT_ATTRIBUTE_REPOSITORY = Symbol(
  'WRITE_PRODUCT_ATTRIBUTE_REPOSITORY',
);
export const READ_PRODUCT_ATTRIBUTE_REPOSITORY = Symbol(
  'READ_PRODUCT_ATTRIBUTE_REPOSITORY',
);

export const PRODUCT_SERVICE = Symbol('PRODUCT_SERVICE');
export const WRITE_PRODUCT_REPOSITORY = Symbol('WRITE_PRODUCT_REPOSITORY');
export const READ_PRODUCT_REPOSITORY = Symbol('READ_PRODUCT_REPOSITORY');
